2025-03-01 01:04:58,449 INFO    MainThread:14936 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:04:58,449 INFO    MainThread:14936 [wandb_setup.py:_flush():67] Configure stats pid to 14936
2025-03-01 01:04:58,449 INFO    MainThread:14936 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:04:58,449 INFO    MainThread:14936 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:04:58,449 INFO    MainThread:14936 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:04:58,449 INFO    MainThread:14936 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\offline-run-20250301_010458-4mdyy56q\logs\debug.log
2025-03-01 01:04:58,450 INFO    MainThread:14936 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\offline-run-20250301_010458-4mdyy56q\logs\debug-internal.log
2025-03-01 01:04:58,450 INFO    MainThread:14936 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000221C1D7FDC0>
2025-03-01 01:04:58,450 INFO    MainThread:14936 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:04:58,450 INFO    MainThread:14936 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-01 01:04:58,450 INFO    MainThread:14936 [wandb_init.py:init():784] starting backend
2025-03-01 01:04:58,674 INFO    MainThread:14936 [wandb_init.py:init():788] sending inform_init request
2025-03-01 01:04:58,686 INFO    MainThread:14936 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-01 01:04:58,687 INFO    MainThread:14936 [wandb_init.py:init():803] backend started and connected
2025-03-01 01:04:58,689 INFO    MainThread:14936 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-01 01:04:58,690 INFO    MainThread:14936 [wandb_init.py:init():896] updated telemetry
2025-03-01 01:04:58,726 INFO    MainThread:14936 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-01 01:04:58,858 INFO    MainThread:14936 [wandb_init.py:init():995] starting run threads in backend
2025-03-01 01:04:59,160 INFO    MainThread:14936 [wandb_run.py:_console_start():2377] atexit reg
2025-03-01 01:04:59,161 INFO    MainThread:14936 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-01 01:04:59,161 INFO    MainThread:14936 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-01 01:04:59,161 INFO    MainThread:14936 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-01 01:04:59,163 INFO    MainThread:14936 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-01 01:04:59,165 INFO    MainThread:14936 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=50
2025-03-01 01:04:59,726 ERROR   MainThread:14936 [internal_api.py:execute():402] 404 response executing GraphQL.
2025-03-01 01:04:59,726 ERROR   MainThread:14936 [internal_api.py:execute():403] {"errors":[{"message":"could not find project bullseye2608-indian-institute-of-technology-madras/uncategorized during createAgent","path":["createAgent"]}],"data":{"createAgent":null}}
2025-03-01 01:05:00,653 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:00,653 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:17,096 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:05:17,101 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:17,102 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:22,676 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:05:22,684 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:22,690 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:22,707 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:05:22,711 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:22,711 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:22,801 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:05:22,807 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:22,808 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:22,829 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:05:22,834 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:22,835 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:28,541 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:05:28,550 INFO    MainThread:14936 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\offline-run-20250301_010528-urn5vidr\logs\debug.log
2025-03-01 01:05:28,550 INFO    MainThread:14936 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\offline-run-20250301_010528-urn5vidr\logs\debug-internal.log
2025-03-01 01:05:28,550 INFO    MainThread:14936 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:05:28,550 INFO    MainThread:14936 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-01 01:05:28,550 INFO    MainThread:14936 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:05:28,552 INFO    MainThread:14936 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=50
2025-03-01 01:05:29,825 ERROR   MainThread:14936 [internal_api.py:execute():402] 404 response executing GraphQL.
2025-03-01 01:05:29,825 ERROR   MainThread:14936 [internal_api.py:execute():403] {"errors":[{"message":"could not find project bullseye2608-indian-institute-of-technology-madras/uncategorized during createAgent","path":["createAgent"]}],"data":{"createAgent":null}}
2025-03-01 01:05:30,006 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:30,006 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:51,902 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:05:51,905 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:51,906 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:51,925 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:05:51,929 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:51,929 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:51,943 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:05:52,368 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:52,368 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:52,412 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:05:52,428 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:52,428 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:52,462 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:05:52,471 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:52,472 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:52,490 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:05:59,021 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:59,021 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:59,032 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:05:59,150 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:05:59,150 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:05:59,173 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:06:00,169 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:06:00,169 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:06:00,188 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:06:00,208 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:06:00,208 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:06:00,224 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:06:00,228 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:06:00,229 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-01 01:06:00,249 INFO    MainThread:14936 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-01 01:06:01,180 INFO    MainThread:14936 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=60
2025-03-01 01:06:02,246 WARNING MsgRouterThr:14936 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-01 01:06:02,248 INFO    MsgRouterThr:14936 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
2025-03-01 01:06:02,317 INFO    Thread-20 (_run_job):14936 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:06:02,317 INFO    Thread-20 (_run_job):14936 [wandb_setup.py:_flush():67] Configure stats pid to 14936
2025-03-01 01:06:02,317 INFO    Thread-20 (_run_job):14936 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:06:02,318 INFO    Thread-20 (_run_job):14936 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:06:02,318 INFO    Thread-20 (_run_job):14936 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:06:02,318 INFO    Thread-20 (_run_job):14936 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010602-5uk0c6v9\logs\debug.log
2025-03-01 01:06:02,318 INFO    Thread-20 (_run_job):14936 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010602-5uk0c6v9\logs\debug-internal.log
2025-03-01 01:06:02,318 INFO    Thread-20 (_run_job):14936 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:06:02,318 INFO    Thread-20 (_run_job):14936 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 32, 'epochs': 5, 'hidden_layers': 4, 'hidden_size': 32, 'learning_rate': 0.0001, 'optimizer': 'sgd', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-01 01:06:02,318 INFO    Thread-20 (_run_job):14936 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:06:02,329 INFO    Thread-20 (_run_job):14936 [wandb_run.py:_finish():2112] finishing run fashion_mnist_hp_search/4mdyy56q
2025-03-01 01:06:02,330 INFO    Thread-20 (_run_job):14936 [wandb_run.py:_finish():2112] finishing run fashion_mnist_hp_search/4mdyy56q
2025-03-01 01:06:12,549 INFO    Thread-23 (_run_job):14936 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:06:12,549 INFO    Thread-23 (_run_job):14936 [wandb_setup.py:_flush():67] Configure stats pid to 14936
2025-03-01 01:06:12,550 INFO    Thread-23 (_run_job):14936 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:06:12,550 INFO    Thread-23 (_run_job):14936 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:06:12,550 INFO    Thread-23 (_run_job):14936 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:06:12,550 INFO    Thread-23 (_run_job):14936 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010612-omcz6wjy\logs\debug.log
2025-03-01 01:06:12,551 INFO    Thread-23 (_run_job):14936 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010612-omcz6wjy\logs\debug-internal.log
2025-03-01 01:06:12,551 INFO    Thread-23 (_run_job):14936 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:06:12,551 INFO    Thread-23 (_run_job):14936 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 32, 'epochs': 5, 'hidden_layers': 4, 'hidden_size': 128, 'learning_rate': 0.001, 'optimizer': 'nesterov', 'weight_decay': 0.5, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-01 01:06:12,551 INFO    Thread-23 (_run_job):14936 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:06:12,551 ERROR   Thread-23 (_run_job):14936 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:06:12,574 INFO    Thread-23 (_run_job):14936 [wandb_run.py:_finish():2112] finishing run fashion_mnist_hp_search/4mdyy56q
2025-03-01 01:06:13,467 INFO    Thread-26 (_run_job):14936 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:06:13,467 INFO    Thread-26 (_run_job):14936 [wandb_setup.py:_flush():67] Configure stats pid to 14936
2025-03-01 01:06:13,467 INFO    Thread-26 (_run_job):14936 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:06:13,467 INFO    Thread-26 (_run_job):14936 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:06:13,467 INFO    Thread-26 (_run_job):14936 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:06:13,468 INFO    Thread-26 (_run_job):14936 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010613-8yz8nnzh\logs\debug.log
2025-03-01 01:06:13,468 INFO    Thread-26 (_run_job):14936 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010613-8yz8nnzh\logs\debug-internal.log
2025-03-01 01:06:13,468 INFO    Thread-26 (_run_job):14936 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:06:13,469 INFO    Thread-26 (_run_job):14936 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 64, 'epochs': 10, 'hidden_layers': 5, 'hidden_size': 128, 'learning_rate': 0.0001, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-01 01:06:13,469 INFO    Thread-26 (_run_job):14936 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:06:13,469 ERROR   Thread-26 (_run_job):14936 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:06:13,478 INFO    Thread-26 (_run_job):14936 [wandb_run.py:_finish():2112] finishing run fashion_mnist_hp_search/4mdyy56q
2025-03-01 01:06:18,620 INFO    MainThread:14936 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:06:18,620 INFO    MainThread:14936 [wandb_init.py:_pause_backend():564] pausing backend
