2025-03-01 01:04:02,314 INFO    Thread-47 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:04:02,315 INFO    Thread-47 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:04:02,316 INFO    Thread-47 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:04:02,316 INFO    Thread-47 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:04:02,317 INFO    Thread-47 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:04:02,317 INFO    Thread-47 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010402-m3lp4bls\logs\debug.log
2025-03-01 01:04:02,319 INFO    Thread-47 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010402-m3lp4bls\logs\debug-internal.log
2025-03-01 01:04:02,319 INFO    Thread-47 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:04:02,320 INFO    Thread-47 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 32, 'learning_rate': 0.001, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-01 01:04:02,320 INFO    Thread-47 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:04:02,321 ERROR   Thread-47 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:04:02,340 INFO    Thread-47 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
2025-03-01 01:04:12,662 INFO    Thread-50 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:04:12,663 INFO    Thread-50 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:04:12,664 INFO    Thread-50 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:04:12,664 INFO    Thread-50 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:04:12,665 INFO    Thread-50 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:04:12,666 INFO    Thread-50 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010412-yud8kmdk\logs\debug.log
2025-03-01 01:04:12,667 INFO    Thread-50 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010412-yud8kmdk\logs\debug-internal.log
2025-03-01 01:04:12,668 INFO    Thread-50 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:04:12,668 INFO    Thread-50 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 128, 'learning_rate': 0.0001, 'optimizer': 'nadam', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-01 01:04:12,669 INFO    Thread-50 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:04:12,670 ERROR   Thread-50 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:04:12,686 INFO    Thread-50 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
