2025-03-01 01:02:56,147 INFO    MainThread:10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:02:56,147 INFO    MainThread:10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:02:56,147 INFO    MainThread:10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:02:56,147 INFO    MainThread:10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:02:56,147 INFO    MainThread:10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:02:56,147 INFO    MainThread:10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010256-7oaeeeoy\logs\debug.log
2025-03-01 01:02:56,148 INFO    MainThread:10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010256-7oaeeeoy\logs\debug-internal.log
2025-03-01 01:02:56,148 INFO    MainThread:10664 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000029A9D78D300>
2025-03-01 01:02:56,148 INFO    MainThread:10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:02:56,148 INFO    MainThread:10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-01 01:02:56,148 INFO    MainThread:10664 [wandb_init.py:init():784] starting backend
2025-03-01 01:02:56,148 INFO    MainThread:10664 [wandb_init.py:init():788] sending inform_init request
2025-03-01 01:02:56,160 INFO    MainThread:10664 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-01 01:02:56,161 INFO    MainThread:10664 [wandb_init.py:init():803] backend started and connected
2025-03-01 01:02:56,162 INFO    MainThread:10664 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-01 01:02:56,164 INFO    MainThread:10664 [wandb_init.py:init():896] updated telemetry
2025-03-01 01:02:56,202 INFO    MainThread:10664 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-01 01:02:56,696 INFO    MainThread:10664 [wandb_init.py:init():995] starting run threads in backend
2025-03-01 01:02:56,991 INFO    MainThread:10664 [wandb_run.py:_console_start():2377] atexit reg
2025-03-01 01:02:56,991 INFO    MainThread:10664 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-01 01:02:56,991 INFO    MainThread:10664 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-01 01:02:56,991 INFO    MainThread:10664 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-01 01:02:56,995 INFO    MainThread:10664 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-01 01:02:56,997 INFO    MainThread:10664 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=50
2025-03-01 01:02:58,341 WARNING MsgRouterThr:10664 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-01 01:02:58,349 INFO    MsgRouterThr:10664 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-01 01:03:00,425 INFO    Thread-14 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:03:00,425 INFO    Thread-14 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:03:00,426 INFO    Thread-14 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:03:00,426 INFO    Thread-14 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:03:00,426 INFO    Thread-14 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:03:00,426 INFO    Thread-14 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010300-xkrbqnpj\logs\debug.log
2025-03-01 01:03:00,427 INFO    Thread-14 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010300-xkrbqnpj\logs\debug-internal.log
2025-03-01 01:03:00,427 INFO    Thread-14 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:03:00,427 INFO    Thread-14 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 5, 'hidden_size': 64, 'learning_rate': 0.0001, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-01 01:03:00,427 INFO    Thread-14 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:03:00,427 ERROR   Thread-14 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:03:00,442 INFO    Thread-14 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
2025-03-01 01:03:04,109 INFO    Thread-17 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:03:04,109 INFO    Thread-17 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:03:04,110 INFO    Thread-17 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:03:04,110 INFO    Thread-17 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:03:04,110 INFO    Thread-17 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:03:04,110 INFO    Thread-17 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010304-mmnsshxl\logs\debug.log
2025-03-01 01:03:04,110 INFO    Thread-17 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010304-mmnsshxl\logs\debug-internal.log
2025-03-01 01:03:04,111 INFO    Thread-17 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:03:04,111 INFO    Thread-17 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-01 01:03:04,111 INFO    Thread-17 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:03:04,111 ERROR   Thread-17 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:03:04,120 INFO    Thread-17 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
2025-03-01 01:03:14,321 INFO    Thread-20 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:03:14,321 INFO    Thread-20 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:03:14,322 INFO    Thread-20 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:03:14,322 INFO    Thread-20 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:03:14,322 INFO    Thread-20 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:03:14,322 INFO    Thread-20 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010314-aalji381\logs\debug.log
2025-03-01 01:03:14,323 INFO    Thread-20 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010314-aalji381\logs\debug-internal.log
2025-03-01 01:03:14,323 INFO    Thread-20 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:03:14,323 INFO    Thread-20 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 32, 'learning_rate': 0.0001, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-01 01:03:14,323 INFO    Thread-20 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:03:14,323 ERROR   Thread-20 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:03:14,332 INFO    Thread-20 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
2025-03-01 01:03:16,754 INFO    Thread-23 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:03:16,754 INFO    Thread-23 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:03:16,755 INFO    Thread-23 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:03:16,755 INFO    Thread-23 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:03:16,755 INFO    Thread-23 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:03:16,756 INFO    Thread-23 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010316-cktsd146\logs\debug.log
2025-03-01 01:03:16,756 INFO    Thread-23 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010316-cktsd146\logs\debug-internal.log
2025-03-01 01:03:16,756 INFO    Thread-23 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:03:16,757 INFO    Thread-23 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 32, 'learning_rate': 0.0001, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-01 01:03:16,757 INFO    Thread-23 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:03:16,757 ERROR   Thread-23 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:03:16,765 INFO    Thread-23 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
2025-03-01 01:03:26,960 INFO    Thread-26 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:03:26,960 INFO    Thread-26 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:03:26,960 INFO    Thread-26 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:03:26,960 INFO    Thread-26 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:03:26,960 INFO    Thread-26 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:03:26,960 INFO    Thread-26 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010326-10w3fdim\logs\debug.log
2025-03-01 01:03:26,961 INFO    Thread-26 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010326-10w3fdim\logs\debug-internal.log
2025-03-01 01:03:26,961 INFO    Thread-26 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:03:26,961 INFO    Thread-26 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 32, 'learning_rate': 0.001, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-01 01:03:26,961 INFO    Thread-26 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:03:26,961 ERROR   Thread-26 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:03:26,968 INFO    Thread-26 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
2025-03-01 01:03:28,042 INFO    Thread-29 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:03:28,043 INFO    Thread-29 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:03:28,043 INFO    Thread-29 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:03:28,043 INFO    Thread-29 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:03:28,043 INFO    Thread-29 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:03:28,044 INFO    Thread-29 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010328-ahdfs415\logs\debug.log
2025-03-01 01:03:28,044 INFO    Thread-29 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010328-ahdfs415\logs\debug-internal.log
2025-03-01 01:03:28,044 INFO    Thread-29 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:03:28,045 INFO    Thread-29 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-01 01:03:28,045 INFO    Thread-29 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:03:28,045 ERROR   Thread-29 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:03:28,053 INFO    Thread-29 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
2025-03-01 01:03:38,227 INFO    Thread-32 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:03:38,228 INFO    Thread-32 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:03:38,228 INFO    Thread-32 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:03:38,228 INFO    Thread-32 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:03:38,228 INFO    Thread-32 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:03:38,229 INFO    Thread-32 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010338-ropturin\logs\debug.log
2025-03-01 01:03:38,229 INFO    Thread-32 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010338-ropturin\logs\debug-internal.log
2025-03-01 01:03:38,229 INFO    Thread-32 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:03:38,230 INFO    Thread-32 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 32, 'learning_rate': 0.0001, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-01 01:03:38,230 INFO    Thread-32 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:03:38,230 ERROR   Thread-32 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:03:38,241 INFO    Thread-32 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
2025-03-01 01:03:39,583 INFO    Thread-35 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:03:39,583 INFO    Thread-35 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:03:39,584 INFO    Thread-35 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:03:39,584 INFO    Thread-35 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:03:39,584 INFO    Thread-35 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:03:39,585 INFO    Thread-35 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010339-xxyyou4i\logs\debug.log
2025-03-01 01:03:39,585 INFO    Thread-35 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010339-xxyyou4i\logs\debug-internal.log
2025-03-01 01:03:39,586 INFO    Thread-35 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:03:39,586 INFO    Thread-35 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 32, 'learning_rate': 0.0001, 'optimizer': 'nadam', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-01 01:03:39,586 INFO    Thread-35 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:03:39,586 ERROR   Thread-35 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:03:39,596 INFO    Thread-35 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
2025-03-01 01:03:49,829 INFO    Thread-38 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:03:49,830 INFO    Thread-38 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:03:49,830 INFO    Thread-38 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:03:49,831 INFO    Thread-38 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:03:49,831 INFO    Thread-38 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:03:49,832 INFO    Thread-38 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010349-g11mb132\logs\debug.log
2025-03-01 01:03:49,833 INFO    Thread-38 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010349-g11mb132\logs\debug-internal.log
2025-03-01 01:03:49,834 INFO    Thread-38 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:03:49,834 INFO    Thread-38 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 32, 'learning_rate': 0.001, 'optimizer': 'nadam', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-01 01:03:49,835 INFO    Thread-38 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:03:49,836 ERROR   Thread-38 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:03:49,859 INFO    Thread-38 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
2025-03-01 01:03:51,045 INFO    Thread-41 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:03:51,045 INFO    Thread-41 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:03:51,046 INFO    Thread-41 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:03:51,046 INFO    Thread-41 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:03:51,047 INFO    Thread-41 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:03:51,048 INFO    Thread-41 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010351-wbdb15o4\logs\debug.log
2025-03-01 01:03:51,049 INFO    Thread-41 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010351-wbdb15o4\logs\debug-internal.log
2025-03-01 01:03:51,049 INFO    Thread-41 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:03:51,049 INFO    Thread-41 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 32, 'learning_rate': 0.0001, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-01 01:03:51,050 INFO    Thread-41 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:03:51,050 ERROR   Thread-41 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:03:51,060 INFO    Thread-41 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
2025-03-01 01:04:01,319 INFO    Thread-44 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:04:01,320 INFO    Thread-44 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:04:01,320 INFO    Thread-44 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:04:01,321 INFO    Thread-44 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:04:01,322 INFO    Thread-44 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:04:01,323 INFO    Thread-44 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010401-xy3lswp6\logs\debug.log
2025-03-01 01:04:01,323 INFO    Thread-44 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010401-xy3lswp6\logs\debug-internal.log
2025-03-01 01:04:01,324 INFO    Thread-44 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:04:01,324 INFO    Thread-44 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 64, 'learning_rate': 0.0001, 'optimizer': 'nadam', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-01 01:04:01,325 INFO    Thread-44 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:04:01,325 ERROR   Thread-44 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:04:01,340 INFO    Thread-44 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
2025-03-01 01:04:02,314 INFO    Thread-47 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:04:02,315 INFO    Thread-47 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:04:02,316 INFO    Thread-47 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:04:02,316 INFO    Thread-47 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:04:02,317 INFO    Thread-47 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:04:02,317 INFO    Thread-47 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010402-m3lp4bls\logs\debug.log
2025-03-01 01:04:02,319 INFO    Thread-47 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010402-m3lp4bls\logs\debug-internal.log
2025-03-01 01:04:02,319 INFO    Thread-47 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:04:02,320 INFO    Thread-47 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 32, 'learning_rate': 0.001, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-01 01:04:02,320 INFO    Thread-47 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:04:02,321 ERROR   Thread-47 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:04:02,340 INFO    Thread-47 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
2025-03-01 01:04:12,662 INFO    Thread-50 (_run_job):10664 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:04:12,663 INFO    Thread-50 (_run_job):10664 [wandb_setup.py:_flush():67] Configure stats pid to 10664
2025-03-01 01:04:12,664 INFO    Thread-50 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:04:12,664 INFO    Thread-50 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:04:12,665 INFO    Thread-50 (_run_job):10664 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:04:12,666 INFO    Thread-50 (_run_job):10664 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010412-yud8kmdk\logs\debug.log
2025-03-01 01:04:12,667 INFO    Thread-50 (_run_job):10664 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010412-yud8kmdk\logs\debug-internal.log
2025-03-01 01:04:12,668 INFO    Thread-50 (_run_job):10664 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:04:12,668 INFO    Thread-50 (_run_job):10664 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 128, 'learning_rate': 0.0001, 'optimizer': 'nadam', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-01 01:04:12,669 INFO    Thread-50 (_run_job):10664 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-01 01:04:12,670 ERROR   Thread-50 (_run_job):10664 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\DELL\.conda\envs\RL\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-01 01:04:12,686 INFO    Thread-50 (_run_job):10664 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/fashion_mnist_hp_search/7oaeeeoy
