2025-02-27 13:10:04,361 INFO    MainThread:11624 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250227_131004-418ypx1x\logs\debug.log
2025-02-27 13:10:04,361 INFO    MainThread:11624 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250227_131004-418ypx1x\logs\debug-internal.log
2025-02-27 13:10:04,361 INFO    MainThread:11624 [wandb_init.py:init():761] calling init triggers
2025-02-27 13:10:04,361 INFO    MainThread:11624 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10, '_wandb': {}}
2025-02-27 13:10:04,366 INFO    MainThread:11624 [wandb_init.py:init():784] starting backend
2025-02-27 13:10:04,366 INFO    MainThread:11624 [wandb_init.py:init():788] sending inform_init request
2025-02-27 13:10:04,369 INFO    MainThread:11624 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-02-27 13:10:04,369 INFO    MainThread:11624 [wandb_init.py:init():803] backend started and connected
2025-02-27 13:10:04,370 INFO    MainThread:11624 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-02-27 13:10:04,370 INFO    MainThread:11624 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: Expecting value: line 1 column 1 (char 0)
2025-02-27 13:10:04,371 INFO    MainThread:11624 [wandb_init.py:init():896] updated telemetry
2025-02-27 13:10:04,372 INFO    MainThread:11624 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-27 13:10:04,863 WARNING MsgRouterThr:11624 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\MLOps\lib\site-packages\wandb\sdk\lib\sock_client.py", line 258, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
BlockingIOError: [WinError 10035] A non-blocking socket operation could not be completed immediately

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\MLOps\lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "c:\Users\DELL\.conda\envs\MLOps\lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "c:\Users\DELL\.conda\envs\MLOps\lib\site-packages\wandb\sdk\lib\sock_client.py", line 262, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\DELL\.conda\envs\MLOps\lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
  File "c:\Users\DELL\.conda\envs\MLOps\lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-27 13:10:04,864 INFO    MainThread:11624 [wandb_init.py:init():995] starting run threads in backend
2025-02-27 13:10:04,865 INFO    MsgRouterThr:11624 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
2025-02-27 13:10:05,189 INFO    MainThread:11624 [wandb_run.py:_console_start():2377] atexit reg
2025-02-27 13:10:05,189 INFO    MainThread:11624 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-27 13:10:05,190 INFO    MainThread:11624 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-27 13:10:05,190 INFO    MainThread:11624 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-27 13:10:05,192 INFO    MainThread:11624 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-27 13:10:05,193 INFO    MainThread:11624 [wandb_run.py:_finish():2112] finishing run bullseye2608-indian-institute-of-technology-madras/my-awesome-project/418ypx1x
2025-02-27 13:10:05,193 INFO    MainThread:11624 [wandb_run.py:_atexit_cleanup():2342] got exitcode: 0
2025-02-27 13:10:05,193 INFO    MainThread:11624 [wandb_run.py:_restore():2324] restore
2025-02-27 13:10:05,193 INFO    MainThread:11624 [wandb_run.py:_restore():2330] restore done
2025-02-27 13:10:08,145 INFO    MsgRouterThr:11624 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-02-27 13:10:08,145 INFO    MainThread:11624 [wandb_run.py:_footer_history_summary_info():3958] rendering history
2025-02-27 13:10:08,145 INFO    MainThread:11624 [wandb_run.py:_footer_history_summary_info():3990] rendering summary
2025-02-27 13:10:08,147 INFO    MainThread:11624 [wandb_run.py:_footer_sync_info():3919] logging synced files
